[package]
name = "epub-reader"
version = "0.1.0"
edition = "2021"

[dependencies]
epub = { path = "./epub-rs" }
rinja = { version = "0.3.5", default-features = false, features = ["humansize", "urlencode"] }
tiny_http = "0.12.0"
